### ISSUE TITLE
Issues that should be improved

### ISSUE THREAD

**Issue by nedoluzhko** [vpc-ccg/circminer#10]
I successfully used your tool but it has several problems:

1. **It is unclear for noobs how to use GFF files from NCBI. (e.g. convertGTF.py doesn't work with Danio rerio annotation GCF_000002035.6_GRCz11_genomic.gff.gz):**

python /home2/artem/bin/circminer/scripts/convertGTF.py GCF_000002035.6_GRCz11_genomic.gtf dtest.gtf
Traceback (most recent call last):
  File "/home2/artem/bin/circminer/scripts/convertGTF.py", line 133, in <module>
    main()
  File "/home2/artem/bin/circminer/scripts/convertGTF.py", line 111, in main
    gid = get_gid(ll)
  File "/home2/artem/bin/circminer/scripts/convertGTF.py", line 15, in get_gid
    return l[l.index('gene_id') + 1]
ValueError: 'gene_id' is not in list

2. **It is impossible to work with the whole genome (GRCz11). As a result, I split chromosome 1 (only 10000 bp).**

circminer -r GCF_000002035.6_GRCz11_genomic.fa -g Danio_rerio.GRCz11.100.gtf -1 R1.fq -2 R2.fq -o dtest
Mon Jul 13 13:00:12 2020 [INFO] Number of threads: 1
Mon Jul 13 13:00:12 2020 [INFO] Input file type: Paired-end
Mon Jul 13 13:00:13 2020 [INFO] Kmer size obtained from index: 14
Mon Jul 13 13:00:13 2020 [INFO] Given kmer size (20) is not equal to the index kmer size (14).
Mon Jul 13 13:00:13 2020 [INFO] Setting kmer size to 14.
Mon Jul 13 13:00:13 2020 [INFO] Loading GTF file...
Mon Jul 13 13:00:18 2020 [INFO] {GTFParser} WARNING: Gene annotation file does not contain any records of some contigs.
Mon Jul 13 13:00:18 2020 [INFO] Completed! (CPU time: 5.98s; Real time: 5.99s)
Mon Jul 13 13:00:18 2020 [INFO] Genome index type: Full
Mon Jul 13 13:00:18 2020 [INFO] Starting read extraction
Mon Jul 13 13:00:18 2020 [INFO] + Loading genome index...
Mon Jul 13 13:00:29 2020 [INFO] + Completed! (CPU time: 11.46s; Real time: 11.51s)
Mon Jul 13 13:00:29 2020 [INFO] + Loading genome sequence...
Mon Jul 13 13:00:31 2020 [INFO] + Completed! (CPU time: 1.94s; Real time: 1.94s)
Mon Jul 13 13:00:31 2020 [INFO] + Starting pseudo-alignment (Round 1)
Segmentation fault (core dumped)

3. **This tool doesn't work with huge fastq files (I tried to analyze rRNA-depleted datasets - 17 Gb)**

circminer -r test.fa -g Danio_rerio.GRCz11.100.gtf -1 1.fq -2 2.fq -o dtest
Mon Jul 13 13:01:29 2020 [INFO] Number of threads: 1
Mon Jul 13 13:01:29 2020 [INFO] Input file type: Paired-end
Mon Jul 13 13:01:30 2020 [INFO] Kmer size obtained from index: 20
Mon Jul 13 13:01:30 2020 [INFO] Loading GTF file...
Mon Jul 13 13:01:35 2020 [INFO] {GTFParser} WARNING: Gene annotation file does not contain any records of some contigs.
Mon Jul 13 13:01:35 2020 [INFO] Completed! (CPU time: 6.28s; Real time: 6.28s)
Mon Jul 13 13:01:35 2020 [INFO] Genome index type: Full
Mon Jul 13 13:01:35 2020 [INFO] Starting read extraction
Mon Jul 13 13:01:35 2020 [INFO] + Loading genome index...
Mon Jul 13 13:01:37 2020 [INFO] + Completed! (CPU time: 2.45s; Real time: 2.45s)
Mon Jul 13 13:01:37 2020 [INFO] + Loading genome sequence...
Mon Jul 13 13:01:37 2020 [INFO] + Completed! (CPU time: 0.01s; Real time: 0.01s)
Mon Jul 13 13:01:37 2020 [INFO] + Starting pseudo-alignment (Round 1)
Segmentation fault (core dumped)

Yours, Artem Nedoluzhko

**Comment by fhach** [comment]
@nedoluzhko Thank you reporting the issues. Most of the reported issues are with the GTF file. We are looking into this.

**Comment by nedoluzhko** [comment]
> @nedoluzhko Thank you reporting the issues. Most of the reported issues are with the GTF file. We are looking into this.

Yes and no. In the first issue, I used gffread-converted GTF from NCBI, but in other issues, I used GTF from [Ensembl](http://www.ensembl.org/Danio_rerio/Info/Index).

**Comment by HosseinAsghari** [comment]
Hi @nedoluzhko,

Regarding your first point, the convertGTF.py script only accepts unzipped GTF or GFF files so please unzip the gzipped file before using the GTF conversion script.

The other two issues you mentioned must be fixed in the latest release.

I'm going to close the issue now but feel free to reopen it if the issue persists or you have other questions.

-Hossein
