### ISSUE TITLE
Command terminated by signal 11 at the very last step

### ISSUE THREAD

**Issue by hoyu310** [vpc-ccg/circminer#13]
Dear CircMiner authors,
I'm experiencing an issue where for some samples the run would seg fault (Command terminated by signal 11) at the very last step before outputting the final list of candidate circRNAs. That is, for runs that are successful, the final output log, as you know is "[INFO] CircRNA detection Completed!" while for the ones that fail they are instead "Command terminated by signal 11" and no .circ_report is generated (the rest of the intermediate files and .pam file are generated).

I'm using the hg38 reference genome and gencode.v29.annotation.gtf from Release 29 (https://www.gencodegenes.org/human/release_29.html). I installed CircMiner through the Bioconda option, and ran it using 25 threads (-t 25), otherwise default parameters. My operating system is Debian GNU/Linux. The available CPU, RAM, and storage are much more than needed.

SRR445016 (Hs68 RNase R+) ran successfully and produced 26720 RNase R+ calls (>= 2 read counts), which is very similar to the result in your paper. However, SRR444975 (Hs68 RNase R-) failed with the seg fault described above. Several other samples I'm interested in and hoping to run CircMiner on, such as SRR1049826 (43,210,654 reads) and SRR1049830 (38,221,008 reads), also failed with the exact same seg fault. Despite that, some other Hs68 samples like SRR444655 and SRR444975 were both successful.

I'm thinking it shouldn't be a too many reads or number of candidates issue, as for example SRR445016 (successful) has 199,922,486 reads and in total almost 50k candidates, while the samples I mentioned that failed have much less of both.

Have you experienced anything similar (the seg fault at that step) while developing the tool? Your help is much appreciated.

**Comment by fhach** [comment]
We will release a new version of circminer to bioconda soon. 
Please try the latest version from Github to see if it still crashes.

**Comment by hoyu310** [comment]
Thanks. I've also tried the installation from source version, and the same error message also at that step occurred.

**Comment by fhach** [comment]
We will check SRR444975 with hg38 and gencode.v29.annotation.gtf to see what is causing the crash. We will keep you posted. Just to make sure that we have everything, please provide the full command line you are using with all the options so we can check this issue.

**Comment by hoyu310** [comment]
Thank you. I just realized there's a typo in my first post. It's supposed to be: "...some other Hs68 samples like SRR444655 and SRR44497**4** were both successful". SRR444975 was the one I couldn't get it to work. Sorry for the possible confusion.

The command lines I used:
circminer --index -r genome.fa -k 20 --thread 25
circminer -r genome.fa -g gencode.v29.annotation.gtf -1 SRR444975_1.fastq.gz -2 SRR444975_2.fastq.gz -o output -t 25

(genome.fa is a fasta file with hg38 chrs1-22, M, X, Y each under a separate header)
(some files are in different directories and for the run I provided the full path to each one, but removed the paths here to be concise)

**Comment by rsoltani97** [comment]
I downloaded the gencode.v29.annotation.gtf through [this link](ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gtf.gz) and downloaded the gencode genome from [this link](ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/GRCh38.primary_assembly.genome.fa.gz).

I tried a few times but I could not reproduce the seg fault using the same command you reported. However, there was a minor bug in the **--index** part which I've solved in [this commit](https://github.com/vpc-ccg/circminer/commit/ec55b741e401dfa33b9abe735fbfc09206153b6a). This commit has been merged with the master branch as well.

Here are my suggestions:
- Make sure that the source of your genome and annotation are same (i.e. both from gencode). 
- Use the latest commit in which I've fixed the index problem and rebuild the index.

Here is my running logs:
./circminer -r ~/GRCh38.primary_assembly.genome.fa -g ~/gencode.v29.annotation.gtf -1 ~/R1.fastq -2 ~/R2.fastq -t 25
Mon May  3 12:00:44 2021 [INFO] Number of threads: 25
Mon May  3 12:00:44 2021 [INFO] Input file type: Paired-end
Mon May  3 12:00:45 2021 [INFO] Kmer size obtained from index: 20
Mon May  3 12:00:45 2021 [INFO] Loading GTF file...
Mon May  3 12:01:37 2021 [INFO] Completed! (CPU time: 49.49s; Real time: 52.38s)
Mon May  3 12:01:37 2021 [INFO] Genome index type: Full
Mon May  3 12:01:37 2021 [INFO] Starting read extraction
Mon May  3 12:01:37 2021 [INFO] + Loading genome index...
Mon May  3 12:01:46 2021 [INFO] + Completed! (CPU time: 5.93s; Real time: 9.20s)
Mon May  3 12:01:46 2021 [INFO] + Loading genome sequence...
Mon May  3 12:01:47 2021 [INFO] + Completed! (CPU time: 1.47s; Real time: 1.47s)
Mon May  3 12:01:47 2021 [INFO] + Starting pseudo-alignment (Round 1)
Mon May  3 12:07:01 2021 [INFO] + Completed round 1! (CPU time: 2103.15s; Real time: 313.66s)
Mon May  3 12:07:01 2021 [INFO] + Loading genome index...
Mon May  3 12:07:10 2021 [INFO] + Completed! (CPU time: 6.30s; Real time: 8.72s)
Mon May  3 12:07:10 2021 [INFO] + Loading genome sequence...
Mon May  3 12:07:11 2021 [INFO] + Completed! (CPU time: 1.44s; Real time: 1.44s)
Mon May  3 12:07:11 2021 [INFO] + Starting pseudo-alignment (Round 2)
Mon May  3 12:16:36 2021 [INFO] + Completed round 2! (CPU time: 2011.08s; Real time: 564.78s)
Mon May  3 12:16:36 2021 [INFO] + Loading genome index...
Mon May  3 12:16:45 2021 [INFO] + Completed! (CPU time: 6.06s; Real time: 8.93s)
Mon May  3 12:16:45 2021 [INFO] + Loading genome sequence...
Mon May  3 12:16:46 2021 [INFO] + Completed! (CPU time: 1.11s; Real time: 1.11s)
Mon May  3 12:16:46 2021 [INFO] + Starting pseudo-alignment (Round 3)
Mon May  3 12:30:23 2021 [INFO] + Completed round 3! (CPU time: 2268.84s; Real time: 816.95s)
Mon May  3 12:30:23 2021 [INFO] Starting circRNA detection
Mon May  3 12:30:23 2021 [INFO] + Sorting remaining read mappings using GNU sort... 
Mon May  3 12:30:33 2021 [INFO] + Completed! (CPU time: 0.04s; Real time: 10.03s)
Mon May  3 12:30:33 2021 [INFO] + Loading genome sequence...
Mon May  3 12:30:35 2021 [INFO] + Completed! (CPU time: 2.07s; Real time: 2.36s)
Mon May  3 12:31:09 2021 [INFO] + Loading genome sequence...
Mon May  3 12:31:12 2021 [INFO] + Completed! (CPU time: 2.02s; Real time: 2.90s)
Mon May  3 12:31:35 2021 [INFO] + Loading genome sequence...
Mon May  3 12:31:38 2021 [INFO] + Completed! (CPU time: 1.67s; Real time: 2.47s)
Mon May  3 12:32:00 2021 [INFO] CircRNA detection Completed! (CPU time: 83.86s; Real time: 87.21s)

**Comment by hoyu310** [comment]
I received Reza's email message via forwarding from GitHub but somehow it doesn't appear here (for me), so I'll include it here for reference:

> I downloaded the gencode.v29.annotation.gtf through this link and downloaded the gencode genome from this link.

> I tried a few times but I could not reproduce the seg fault using the same command you reported. However, there was a minor bug in the --index part which I've solved in this commit. This commit has been merged with the master branch as well.

> Here are my suggestions:

> Make sure that the source of your genome and annotation are same (i.e. both from gencode).

> Use the latest commit in which I've fixed the index problem and rebuild the index.

> Here is my running logs:

> ./circminer -r ~/GRCh38.primary_assembly.genome.fa -g ~/gencode.v29.annotation.gtf -1 ~/R1.fastq -2 ~/R2.fastq -t 25



First, thanks for helping me out. I took your suggestion of using a genome and annotation from the same source. From Gencode v29 (https://www.gencodegenes.org/human/release_29.html), I downloaded and re-indexed with GRCh38.primary_assembly.genome.fa. Although using gencode.v29.annotation.gtf still didn't work for me, I downloaded and used gencode.v29.primary_assembly.annotation.gtf as the annotation, and that resolved the issue! Maybe because now the genome and annotation are fully corresponding to each other. All runs complete successfully now. Thank you!
