### ISSUE TITLE
annotate_transcript.py 

### ISSUE THREAD

**Issue by heartlncrna** [vpc-ccg/circminer#15]
I’m testing your CircMiner using your examples. I ran into this error:

$ python ../scripts/annotate_transcript.py output.circ_report ref.gtf output.circ_report.annotated
File "../scripts/annotate_transcript.py", line 7
<!DOCTYPE html>
^
SyntaxError: invalid syntax

The above error appear on both Python 2.7.15 and Python 3.9.6.

Would you mind telling me how to fix this error?

Thank you very much.

**Comment by rsoltani97** [comment]
I couldn't reproduce the error. However, it is a SyntaxError pointing to an empty line, and I guess it relates to an indentation issue.

**Comment by heartlncrna** [comment]
Thanks. I solved the issue. I somehow downloaded the GitHub HTML file.
