### ISSUE TITLE
remain_R1/2.fastq files

### ISSUE THREAD

**Issue by EricSHo** [vpc-ccg/circminer#2]
Hi,

What are those *remain_R1/2. fastq files? Are they required for downstream analysis?

Additionally, what are the *remain_R1/2. fastq.srt files? I have 3 paired-end replicates, why only one pair of *srt files was created?

Thanks, Eric.

**Comment by HosseinAsghari** [comment]
Hi Eric,

The files you mentioned are temporary files and will not be needed for downstream analysis. 

You should check the files mentioned [here](https://github.com/vpc-ccg/circminer#output-files) in CircMiner's Readme file. The most important output you need for circRNA analysis will be the `.circ_report` file that contains the breakpoints, number of supporting back-splice junction reads and some other useful information.

If you want to add annotations to `.circ_report` file you can run the script described [here](https://github.com/vpc-ccg/circminer#annotate-circminers-output-file).
