### ISSUE TITLE
invalid next size (normal): 0x0000000246812290

### ISSUE THREAD

**Issue by vokuryshev** [vpc-ccg/circminer#6]
Dear Authors,

testing your tool with my data (10m paired-end reads) I got the following message almost at the end of my run:

*** Error in `/usr/bin/circminer': free(): invalid next size (normal): 0x0000000246812290 ***
/var/spool/slurmd/job408741/slurm_script: line 23: 23897 Aborted
circminer --sam 
--thread 8 
--rlen 75 
--reference $1 
--gtf $2 
--output $3 
--seq1 $4 
--seq2 $5 
--scan-lev 1

would it could be?
thank you.

Vladimir

**Comment by fhach** [comment]
Related to #7.
