### ISSUE TITLE
ERROR: ... length of sequence (75) does not match with quality (76)!

### ISSUE THREAD

**Issue by vokuryshev** [vpc-ccg/circminer#7]
hi, 
running CircMiner 0.4.3 with the following settings:

circminer --sam
--thread 8
--reference $1
--gtf $2
--output $3
--seq1 $4
--seq2 $5
--scan-lev 1

I am getting similar message for all  my samples :
ERROR: read: K00302:28:HJCVNBBXX:4:1104:30888:46750, length of sequence (75) does not match with quality (76)!
Aborting

I checked my original fastq.gz and didn't  find any length mismatch (seq & quality strings) there. however I could observe this problem in temporary fastq files, created by circminer. the program aborted at the  Round 2 and the length mismatch occurs in _1_remain_R1.fastq

would you please help to solve this issue?

thank you.

Vladimir

there is no such 
but I find it in fastq fiiles

**Comment by fhach** [comment]
Please post the mates of the original read `K00302:28:HJCVNBBXX:4:1104:30888:46750` and its quality values from both original and temp files.

**Comment by vokuryshev** [comment]
Hi Hossein,

sorry, i deleted the previous run.. re-running  I got similar error with another read: 
ERROR: read: K00302:28:HJCVNBBXX:4:1108:27225:40719, length of sequence (76) does not match with quality (75)!
Aborting

hope you can see the text properly in terminal:
```::::::::::::::
0_R1.read
::::::::::::::
@K00302:28:HJCVNBBXX:4:1108:27225:40719 1:N:0:AGTTCC
GGAAAGGGTTTATTCGGCTTACATTTCCATACTGCTGTTCATCACCAAGGAAGTCAGGACTGGAACTCAAGCAGGT
+
AAFFFJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJA
::::::::::::::
0_R2.read
::::::::::::::
@K00302:28:HJCVNBBXX:4:1108:27225:40719 2:N:0:AGTTCC
GAAAGGAGCTTCAGTTGAGGAAATACCTCCATGAGATCCAGCTGCAAGGCATTTTCTCAATTAGTGATCAAGGGA
+
AAAFFJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJFJFJJJJJJJJFJJJJJJJJJJJJ
::::::::::::::
1_remain_R1.read
::::::::::::::
@K00302:28:HJCVNBBXX:4:1108:27225:40719 * 8 * * * * * * * * * * * * * * * * * * * *
GGAAAGGGTTTATTCGGCTTACATTTCCATACTGCTGTTCATCACCAAGCATTCTCTATTCTCTCCCACCTTTTC
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
::::::::::::::
1_remain_R2.read
::::::::::::::
@K00302:28:HJCVNBBXX:4:1108:27225:40719 * 8 * * * * * * * * * * * * * * * * * * * *
GAAAGGAGCTTCAGTTGAGGAAATACCTCCATGAGATCCAGCTGCAAGGCATTTTCTCAATTAGTGATCAAGGGA
+
AAAFFJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJFJFJJJJJJJJFJJJJJJJJJJJJ
```
interrupted 2_remain_R1.fastq & 2_remain_R2.fastq don't have reads.

surprisingly, I see that the original paired reads have different lengths! may be this is the problem?
will try to trim all equally and then re-run your tool.

v.

**Comment by vokuryshev** [comment]
0_R1.read & 0_R2.read are from original files

**Comment by vokuryshev** [comment]
in addition 0_R1.read is different from 1_remain_R1.read.
why?

**Comment by fhach** [comment]
Please trim all your reads and quality scores to the same length and try again. If if crashes we can take a look into. 

Also you can use ``` tag to create a block and paste your data when sharing. I updated your post.

```
>1
Like this
```

**Comment by HosseinAsghari** [comment]
Hi Vladimir,

Are you passing _--rlen 75_ to CircMiner when you run it on this data? 
Because from the paired-end read you shared I see that R1 has 76 bp and R2 has 75 bp. This can cause a problem since rlen specifies the maximum read length and in this specific read one mate has a longer length.

-Hossein

**Comment by vokuryshev** [comment]
Dear Hossein,

sorry for the delay with my response and thanks for your kind assistance and tips in posting my questions :)

I would like to share results of my tests which hopefully could  help to de-bug the tool:

1) I checked all reads in my input file  with the following below onliner and can confirm that all reads are fine means  have pair-wise equal lengths of sequence and quality strings.
```
zcat input.fq.gz | awk '{if(NR%4==1||NR%4==0||NR%4==2) print $1, length($1)}' | paste - - - | awk '$4!=$6 {print $1"\n"$3"\n+\n"$5}' > input.unequal.fq`
```
the result is zero means: no difference in seq. and qual. strings lengths

2) I ran your circminer 3 times with the same input and parameters without any change in configuration:
```
$circminer \
--thread 16 \
--reference $1 \
--gtf $2 \
--output $3 \
--seq1 $4 \
--seq2 $5 \
--scan-lev 2
```
and got 3 different  errors but of the  same type:
```
ERROR: read: K00302:28:HJCVNBBXX:4:1103:23510:5798, length of sequence (75) does not match with quality (76)!
Aborting
..
ERROR: read: K00302:28:HJCVNBBXX:4:1223:24627:18775, length of sequence (75) does not match with quality (76)!
Aborting
..
ERROR: read: K00302:28:HJCVNBBXX:4:1109:25499:13078, length of sequence (76) does not match with quality (75)!
Aborting
```
3) here are those reads from input file:

```
@K00302:28:HJCVNBBXX:4:1103:23510:5798 1:N:0:AGTTCC
GGGTAGTGTTCCTTCTGTTTCTATTTTGTGGAATAGTTTGAACAATATTGGTATTAGGTCTTCTTTGTAGGTCTG
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
@K00302:28:HJCVNBBXX:4:1103:23510:5798 2:N:0:AGTTCC
GTCCCATATCCTCTAAAGAAATAGAAGCAATCATTAAAAGTCTCCCAACAACAATAACCCCCAAGACGAGATGGTT
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJ
@K00302:28:HJCVNBBXX:4:1223:24627:18775 1:N:0:AGTTCC
GGCGTTCCAAACCACGGTCATCTCTTCTTTGCTTACTTTAGTGACTTCTGGAGGATCAGGGCGGCCAGGTCTGTC
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJ
@K00302:28:HJCVNBBXX:4:1223:24627:18775 2:N:0:AGTTCC
AAGAAACCTGAAAATCACTGATGTGTCCAGTGACAGGTGTACTATCCGCTGGGATCCACCAGAAGATGATGGCGGC
+
AAFFAJJJJJJJJJJJJJFJFJJJJJJJJJJJFJJJJJJJJJJ-FJ<JJJJJJJJJJJJJJJJJJJJJJJFJJJJJ
@K00302:28:HJCVNBBXX:4:1109:25499:13078 1:N:0:AGTTCC
CAGGCTTATATAGTAAAACTCAAAGGGGGAGAACTGGGCAGAGAAAGTACAAGTTTACATCACTAGGGAGTTCTGC
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
@K00302:28:HJCVNBBXX:4:1109:25499:13078 2:N:0:AGTTCC
CATGGCTCCTTAGTTACGTAGATTCCTTTGGCAGAACTCCCTAGTGATGTAAACTTGTACTTTCTCTGCCCAGTTC
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
```

4) here are those reads from output  files for R1:
```
##### test.01 #####

r1.t_1:

@K00302:28:HJCVNBBXX:4:1103:23510:5798 * 9 * * * * * * * * * * * * * * * * * * * *
GGGTAGTGTTCCTTCTGTTTCTATTTTGTGGAATAGTTTGAAATGAGTTGGATAAAACAATTCCGGTTAGACCAC
+
<AFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ

r1.t_2:

READ NOT FOUND


##### test.02 #####

r1.t_1:

@K00302:28:HJCVNBBXX:4:1223:24627:18775 * 13 * * * * * * * * * * * * * * * * * * * *
GGCGTTCCAAACCACGGTCATCTCTTCTTTGCTTACTTTAGTGACTTCTGGAGGATCAGGGCGGCCAGGTCTGTC
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJ

r1.t_2:

@K00302:28:HJCVNBBXX:4:1223:24627:18775 1423887573 0 2 76765947 76766021 75 1 75 + 0 2 76766226 76766301 76 1 76 - 0 3
55 0 1 1
GGCGTTCCAAACTGGGTAGTCTGAGTAGCGTCGTGGTATTCCTGAAAGGCCCAGGAAATGTTGAGGGAAGAATGT
+
AAFFFJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ

r1.t_3:

READ NOT FOUND

##### test.03 #####
r1.t_1:

@K00302:28:HJCVNBBXX:4:1109:25499:13078 720915966 7 14 32115548 32115623 76 1 76 - 0 14 32115518 32115593 76 1 76 + 0 
106 0 0 0
CAGGCTTATATAGTAAAACTGACTACCCTACGTTCTCCTACAATGGACCTTGAGAGCTTGTTTGGAGGTTCTAGC
+
AAAFFJJJJJJJJJJJJJJJJJJJJJJJJFFJJJJJJJJJJJJJJJJJJJJJJJ7JJF<JJFFFJJJJJJJFJJJ

r1.t_2:

READ NOT FOUND
```

NOTE: t_1 & t_2 correspond to your prefixes t_1_remain & t_2_remain

5) all R2 reads are identical to original / input file

6) if you compare the sequences they are different on both sequence and quality level

my questions are:

(I) Why running the tool with the same conditions produces different results?
(II) Why the sequence data are changed?
(III) Any hope to fix this?

If you need more info please let me know.

Thank you for your help!

Vladimir

**Comment by fhach** [comment]
Thanks @vokuryshev, I assume this is a private dataset?

**Comment by vokuryshev** [comment]
Hi Hossein,

do you want to see original input files? they are (R1 & R2) ~2.5Gb and ~2.7G each, respectively. I guess I  can upload them to your place if it helps  for your investigation.

v.

**Comment by fhach** [comment]
Indeed  I can share you a location to upload.

**Comment by vokuryshev** [comment]
good :)

**Comment by fhach** [comment]
I need an email to send you an invite. You can find my email on the paper.

**Comment by fhach** [comment]
@vokuryshev, shared the link.

**Comment by vokuryshev** [comment]
the reads are in the dropbox. please let me know when you finish with download. thanks.

**Comment by radanika** [comment]
Dear Hossein,
did you have a chance to take a look on my dataset? at least did you download it from Dropbox? 
thanks.
v.

**Comment by vokuryshev** [comment]
sorry, I sent my inquiry from another git-account (radanika)..anyway hope to get your response.
v.

**Comment by fhach** [comment]
hi @vokuryshev, can you give it a shot for multi-thread version. I believe it is fixed in the recent commit.

**Comment by danphillips28** [comment]
I have also run into this issue, and have also found that it does not seem to be deterministic. i.e., I have now run circminer 5 times on the same 10 samples, whilst playing around with parameters, and have found sometimes an error is produced and other times it is not produced. Kind of strange. Was any progress made on this puzzling error? Thank you!
